# Generated by Django 5.1.6 on 2025-04-18 14:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_newspost_delete_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
