# Generated by Django 5.1.6 on 2025-05-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_newspost_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='newspost',
            options={'ordering': ['-published_date']},
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='category',
        ),
        migrations.AddField(
            model_name='newspost',
            name='summary',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='news_posts', to='app.tag'),
        ),
    ]
